CREATE TABLE IF NOT EXISTS `agent_schedule_run` (
  `run_id` bigint NOT NULL AUTO_INCREMENT COMMENT '运行ID',
  `run_no` varchar(64) NOT NULL COMMENT '运行编号',
  `trigger_type` varchar(32) NOT NULL COMMENT '触发类型',
  `stage` varchar(32) NOT NULL COMMENT '当前阶段',
  `status` varchar(16) NOT NULL COMMENT '运行状态',
  `model_provider` varchar(32) DEFAULT NULL COMMENT '模型提供方',
  `model_name` varchar(100) DEFAULT NULL COMMENT '模型名称',
  `week_start` date NOT NULL COMMENT '排班周开始日期',
  `week_end` date NOT NULL COMMENT '排班周结束日期',
  `perceived_doctor_count` int DEFAULT 0 COMMENT '感知医生数',
  `perceived_dept_count` int DEFAULT 0 COMMENT '感知科室数',
  `generated_count` int DEFAULT 0 COMMENT '生成班次数',
  `inserted_count` int DEFAULT 0 COMMENT '入库班次数',
  `fallback_count` int DEFAULT 0 COMMENT '兜底次数',
  `warning_count` int DEFAULT 0 COMMENT '告警次数',
  `duration_ms` bigint DEFAULT 0 COMMENT '运行耗时毫秒',
  `perception_summary` text COMMENT '感知摘要',
  `reasoning_summary` text COMMENT '推理摘要',
  `action_summary` text COMMENT '执行摘要',
  `warning_summary` text COMMENT '告警摘要',
  `error_message` text COMMENT '异常信息',
  `start_time` datetime NOT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  PRIMARY KEY (`run_id`),
  UNIQUE KEY `uk_agent_schedule_run_no` (`run_no`),
  KEY `idx_agent_schedule_run_week` (`week_start`, `week_end`),
  KEY `idx_agent_schedule_run_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='智能体排班运行记录表';
